/* Modelagem Básica - 
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* APRESENTA A BASE DE DADOS EXISTENTE */
SHOW DATABASES;

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E 02 - AD ADM DE DADOS */

MODELAGE CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* SCRIPT - INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS*/

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */
DESC CLIENTE;

/*
 * NO FLOAT NO BANCO DE DADOS, NO CASO DE float(7,3) são sete casas no total sendo três depois da vírgula
 * ENUM só existe no mysql
 */

